### ISSUE TITLE
builds ok, but insmod and test always failed

### ISSUE THREAD

**Issue by kotee4ko** [out-of-tree/out-of-tree#22]
Hello.

Thanks for you're hard work.

Can you explain me, please, what I'm doing wrong? 
![image](https://user-images.githubusercontent.com/62266948/103988904-8187bc00-5197-11eb-9495-c848b29f8adb.png)

**Comment by kotee4ko** [comment]
Thanks for fast and operative reply!

After reading you're answer I think about versions can be outdated because of using centOS repos...
So, I update qemu version, build it from sources.

Nothing changed.  
![image](https://user-images.githubusercontent.com/62266948/104072076-1a0f5200-5213-11eb-8604-3f7c2161cd76.png)


I think, that problem is in my not-understanding of .out-of-tree's Makefile content and logic of test algorithm... 
May be you can explain it for me, please?
>># out-of-tree called make with two arguments -- kernel headers path and name
Who passes this two arguments? Or from where .out-of-tree gets it? Or they are passed automatically?

>> # of target binary that MUST be produced by makefile
Is it get it from define `TARGET` in Makefile ?

>> # - $(TARGET).ko_test: name of test binary that MUST be produced by makefile
If `TARGET` define is name of our binary, and name of our binary is `example.ko` why we pass `$(TARGET).ko_test`  ?
On this line my mind throw Oops ;D

and next line in `all:` case are uncleared:
>> cp test.sh $(TARGET)
Are we copy `test.sh` rewriting our compiled LKM? What???

Thanks)

root@IS-73100:/# **qemu-system-x86_64 -version** <-- from sources
```
QEMU emulator version 5.2.50 (v5.2.0-901-ge79de63)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

root@IS-73100:/# **docker version**  <== from centos epel repo
```

Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:16:13 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@IS-73100:/# 
```


root@IS-73100:/# **go version**
`go version go1.15.5 linux/amd64`  <-- from centos epel repo


games@IS-73100:~/.out-of-tree/examples/kernel-module$ **out-of-tree log dump | head -n 34**
```
ID: 144
Date: 2021-01-08 22:18:23 +0000 UTC
Tag: 

Type: module
Name: example

Distro: Ubuntu 18.04
Kernel: 4.15.0-24-generic

Build ok: true
Insmod ok: false
Test ok: false

Build output:
make -C /lib/modules/4.15.0-24-generic/build M=/work modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-24-generic'
  CC [M]  /work/example.o
  LD [M]  /work/8714207374866315668_4.15.0-24-generic.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /work/8714207374866315668_4.15.0-24-generic.mod.o
  LD [M]  /work/8714207374866315668_4.15.0-24-generic.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-24-generic'
cp test.sh 8714207374866315668_4.15.0-24-generic


Insmod output:


Test output:


Qemu stdout:

```

**Comment by kotee4ko** [comment]
And one more question. Where can I found builded *.ko raw modules?

**Comment by jollheef** [comment]
Can't reproduce the issue on the fresh CentOS 7 installation.

> And one more question. Where can I found builded *.ko raw modules?

You can use the `--dist` flag for `out-of-tree pew` to specify the directory where the build results will be saved.

**Comment by jollheef** [comment]
Feel free to reopen it if it's still relevant.
